[project]
name = "clipster-server"
version = "0.6.0"
description = "Multi Platform Cloud Clipboard - Linux Server"
authors = [
    { name = "MC51", email = "mc@data-dive.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
    "djangorestframework>=3.18",
    "gunicorn>=26.2",
    "whitenoise>=6.12",
]
