# Generated by Django 4.0.2 on 2022-02-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipster', '0002_auto_20201214_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='format',
            field=models.CharField(blank=True, default='txt', max_length=3),
        ),
    ]
