# Generated by Django 4.0.2 on 2022-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipster', '0003_clip_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='text',
            field=models.TextField(max_length=7340032.0),
        ),
    ]
